### ISSUE TITLE
This repository will be archived in a few days!

### ISSUE THREAD

**Issue by jcnetdev** [apollonian11/reactriot2017-reaction#55]
Hello fellow hacker! Thanks for participating in our most recent competition.

We're opening this issue to let you know that we'll be archiving this repository on August 17. Please be sure to [migrate it](https://help.github.com/articles/transferring-a-repository/) to your personal GitHub account before that happens so you don't lose any data!

Let us know if this is problematic for any reason. We're happy to help. Email us at hello@hackbit.co

**Comment by apollonian11** [comment]
Transferred the repository. ✌️
